### ISSUE TITLE
Description of extension on marketplace is a bit misleading

### ISSUE THREAD

**Issue by Gert-dev** [LukeGeneva/vscode-auto-collapse-explorer#3]
On the extension marketplace it says "Auto-collapse explorer directories not currently in use", but that is not really what this extension does. The README mentions the same, but then goes on it to describe it correctly: "When focus changes to a new document, that document is revealed in the file tree and all other open folders are collapsed."

What the other part of the description implies is that all folders that contain files currently opened in some editor remain open at all times, like [this Atom extension](https://github.com/Greenek/atom-tree-view-auto-collapse). For example, with the following tree:

* Folder1
    * A.txt
* Folder2
    * B.txt
* Folder3
    * C.txt

With no files open, opening and activating the editor for `A.txt` will expand `Folder1` and collapse `Folder2` and `Folder3`. If you now open and activate the editor for `B.txt`, `Folder2` will be expanded, but `Folder1` will not collapse because `A.txt` wasn't closed. As soon as you close `A.txt`, `Folder1` will collapse.

Would such a thing be possible? This behavior is also exhibited by the above Atom extension and is really handy as it keeps all _relevant_ trees open, instead of just the tree of the _active_ editor.

Thanks!

**Comment by arafatzahan** [comment]
@Gert-dev Have you ever find anything like that you've described here?

**Comment by Gert-dev** [comment]
@arafatzahan Unfortunately not - I still miss this from Atom.

**Comment by arafatzahan** [comment]
Ah the tragedy : (

**Comment by LukeGeneva** [comment]
I've updated the README in the latest release. I do agree that behavior described here would be pretty handy. Feel free to open a separate issue with that as a feature request.

**Comment by Gert-dev** [comment]
Thanks for the information and update!

I created #12 as a separate issue.
