### ISSUE TITLE
Explorer opens when in Zen Mode

### ISSUE THREAD

**Issue by johnschult** [LukeGeneva/vscode-auto-collapse-explorer#4]
The extension should probably be checking to see if Zen Mode is activated before firing. However, according to https://github.com/microsoft/vscode/issues/89278, it looks like that *might* not be available to your extension. Not sure of the way it is implemented...

**Comment by LukeGeneva** [comment]
Unfortunately, that does look like the case. There are a couple things that seem like they would make this extension much easier to maintain and allow it to behave better -- such as having access from the extension to [when clauses](https://code.visualstudio.com/api/references/when-clause-contexts) and being able to tell whether the Explorer viewlet is visible or not.

If anyone comes across this issue in the future and knows how to access these things from an extension, please let me know.

I'll close this issue for now with the intention of re-addressing it if these features become available, or I find out something different. Thanks!
